### ISSUE TITLE
Util.hのstepを実行すると読み取りアクセス違反となる。

### ISSUE THREAD

**Issue by dicenull** [s1500729/MeglimathSimulator#14]
Util.h内
inline const std::vector<int> &step(size_t n) {
	auto v = std::vector<int>(n);
	std::iota(v.begin(), v.end(), n);
	return v;
}
を実行後、
例外がスローされました:読み取りアクセス違反。
**<begin>$L0** が 0xFFFFFFFFFFFFFFFF でした。
というエラーが発生する。

**Comment by Y-Sasaki-apple** [comment]
凡ミス失礼しました。
以下の内容で入れ替えてください。たぶん動作すると思います。
https://gist.github.com/bamboowonsstring/a6c346d78c76902fc8c2d037864635aa
