### ISSUE TITLE
ゲームロジック条件の整理について

### ISSUE THREAD

**Issue by Y-Sasaki-apple** [s1500729/MeglimathSimulator#22]
条件の表記がすさまじいことになっているので、なるべくシンプルになるようにします。

**Comment by Y-Sasaki-apple** [comment]
ゲームのLogic部分ですけど、自分の独断で書き換えて大丈夫でしょうか。
多少見づらい部分が増えるかもしれませんが…

**Comment by dicenull** [comment]
自分でも整理したかった部分なので大丈夫です。お願いします
